# -*- coding: utf-8 -*-
"""Ray-tracer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uC-vsEv7-2tDzRZmjP8CQRpYGswt9spx
"""

import numpy as np
from renderer.vector import reflect
from renderer.ray import Ray

class Renderer:
    def __init__(self, scene, camera, max_depth=3):
        self.scene = scene
        self.camera = camera
        self.max_depth = max_depth

    def trace(self, ray, depth):
        if depth > self.max_depth:
            return np.array([0, 0, 0])

        hit_obj = None
        min_t = float("inf")
        hit_point = None
        normal = None

        # Find closest intersection
        for obj in self.scene.objects:
            result = obj.intersect(ray)
            if result:
                t, p, n = result
                if t < min_t:
                    min_t = t
                    hit_obj = obj
                    hit_point = p
                    normal = n

        # Background color
        if hit_obj is None:
            return np.array([0.2, 0.7, 1.0])

        view_dir = -ray.direction
        color = 0.1 * hit_obj.color  # Ambient

        for light in self.scene.lights:
            light_dir = light.position - hit_point
            light_dist = np.linalg.norm(light_dir)
            light_dir = light_dir / light_dist

            # 🔥 SHADOW CHECK
            shadow_ray = Ray(hit_point + 1e-5 * normal, light_dir)
            in_shadow = False

            for obj in self.scene.objects:
                shadow_hit = obj.intersect(shadow_ray)
                if shadow_hit:
                    t_shadow, _, _ = shadow_hit
                    if t_shadow < light_dist:
                        in_shadow = True
                        break

            if in_shadow:
                continue

            # Diffuse
            diff = max(np.dot(normal, light_dir), 0)
            diffuse = diff * hit_obj.color * light.intensity

            # Specular (Phong)
            reflect_dir = reflect(-light_dir, normal)
            spec = max(np.dot(view_dir, reflect_dir), 0) ** 32
            specular = spec * light.intensity * np.array([1, 1, 1])

            color += diffuse + specular

        # 🔁 REFLECTION
        reflect_dir = reflect(ray.direction, normal)
        reflect_ray = Ray(hit_point + 1e-5 * normal, reflect_dir)
        reflect_color = self.trace(reflect_ray, depth + 1)

        color = (1 - hit_obj.reflection) * color + hit_obj.reflection * reflect_color

        return np.clip(color, 0, 1)

    def render(self):
        width, height = self.camera.width, self.camera.height
        image = np.zeros((height, width, 3))

        for y in range(height):
            for x in range(width):
                ray = self.camera.get_ray(x, y)
                image[y, x] = self.trace(ray, 0)

        return image

"""First, we need to create the `renderer` directory. This will house our custom `vector` and `ray` modules."""

import os

if not os.path.exists('renderer'):
    os.makedirs('renderer')
    print('Created directory: renderer')
else:
    print('Directory renderer already exists.')

"""Next, let's create the `vector.py` file inside the `renderer` directory. This file will contain the `reflect` function."""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile renderer/vector.py
# import numpy as np
# 
# def reflect(vector, normal):
#     return vector - 2 * np.dot(vector, normal) * normal

"""Finally, we'll create the `ray.py` file in the `renderer` directory. This will define the `Ray` class."""

class Sphere:
    def __init__(self, center, radius, color, reflection):
        self.center = np.array(center)
        self.radius = radius
        self.color = np.array(color) / 255.0 # Normalize color
        self.reflection = reflection

    def intersect(self, ray):
        oc = ray.origin - self.center
        a = np.dot(ray.direction, ray.direction)
        b = 2 * np.dot(oc, ray.direction)
        c = np.dot(oc, oc) - self.radius**2
        discriminant = b*b - 4*a*c

        if discriminant < 0:
            return None
        else:
            t0 = (-b - np.sqrt(discriminant)) / (2*a)
            t1 = (-b + np.sqrt(discriminant)) / (2*a)

            if t0 > 1e-6: # Check for positive t to avoid self-intersection
                t = t0
            elif t1 > 1e-6:
                t = t1
            else:
                return None

            hit_point = ray.origin + t * ray.direction
            normal = (hit_point - self.center) / self.radius
            return t, hit_point, normal

class Light:
    def __init__(self, position, intensity):
        self.position = np.array(position)
        self.intensity = intensity

class Camera:
    def __init__(self, position, look_at, fov, width, height):
        self.position = np.array(position)
        self.width = width
        self.height = height

        aspect_ratio = float(width) / height
        angle = np.tan(np.deg2rad(fov / 2.0))

        self.forward = (look_at - position)
        self.forward = self.forward / np.linalg.norm(self.forward)

        self.right = np.cross(self.forward, np.array([0, 1, 0])) # Assuming Y is up
        self.right = self.right / np.linalg.norm(self.right)
        if np.dot(self.right, self.right) == 0: # Handle straight up/down camera
             self.right = np.array([1, 0, 0])

        self.up = np.cross(self.right, self.forward)
        self.up = self.up / np.linalg.norm(self.up)

        self.plane_width = 2 * angle * aspect_ratio
        self.plane_height = 2 * angle

    def get_ray(self, x, y):
        u = (x + 0.5) / self.width
        v = (y + 0.5) / self.height

        x_coord = (2 * u - 1) * self.plane_width / 2.0
        y_coord = (1 - 2 * v) * self.plane_height / 2.0

        ray_direction = self.forward + x_coord * self.right + y_coord * self.up
        return Ray(self.position, ray_direction)

class Scene:
    def __init__(self, objects, lights):
        self.objects = objects
        self.lights = lights

# Define scene objects and lights based on the JSON data
scene_data = {'objects': [{'type': 'sphere', 'center': [0, 0, -5], 'radius': 1, 'color': [255, 0, 0], 'reflection': 0.5}, {'type': 'sphere', 'center': [2, 0, -6], 'radius': 1, 'color': [0, 255, 0], 'reflection': 0.3}, {'type': 'sphere', 'center': [-2, 0, -6], 'radius': 1, 'color': [0, 0, 255], 'reflection': 0.7}], 'lights': [{'position': [5, 5, -10], 'intensity': 1.5}, {'position': [-5, 5, -8], 'intensity': 1.0}]}

objects = []
for obj_data in scene_data['objects']:
    if obj_data['type'] == 'sphere':
        objects.append(Sphere(obj_data['center'], obj_data['radius'], obj_data['color'], obj_data['reflection']))

lights = []
for light_data in scene_data['lights']:
    lights.append(Light(light_data['position'], light_data['intensity']))

scene = Scene(objects, lights)

# Define a camera
camera_position = np.array([0, 0, 0])
camera_look_at = np.array([0, 0, -1])
camera_fov = 90
camera_width = 400
camera_height = 300

camera = Camera(camera_position, camera_look_at, camera_fov, camera_width, camera_height)

# Instantiate the renderer
renderer = Renderer(scene, camera)

# Render the image
image = renderer.render()

# Display the image (using matplotlib or PIL)
import matplotlib.pyplot as plt
plt.imshow(image)
plt.axis('off')
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %%writefile renderer/ray.py
# import numpy as np
# 
# class Ray:
#     def __init__(self, origin, direction):
#         self.origin = np.array(origin)
#         self.direction = np.array(direction) / np.linalg.norm(direction)

{
  "objects": [
    {"type": "sphere", "center": [0, 0, -5], "radius": 1, "color": [255, 0, 0], "reflection": 0.5},
    {"type": "sphere", "center": [2, 0, -6], "radius": 1, "color": [0, 255, 0], "reflection": 0.3},
    {"type": "sphere", "center": [-2, 0, -6], "radius": 1, "color": [0, 0, 255], "reflection": 0.7}
  ],
  "lights": [
    {"position": [5, 5, -10], "intensity": 1.5},
    {"position": [-5, 5, -8], "intensity": 1.0}
  ]
}